[package]
name = "dnb"
version = "0.2.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.20.0", features = ["extension-module"] }
rand = "0.8.4"
colored = "2.0.4"

[build-dependencies]
maturin = "1.2.3"

[[bin]]
name = "main"
path = "src/main.rs"

# this breaks it for some reason
[lib]
name = "dnb"
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "dnb"
rustc-extra-args = ["--cfg", "feature=\"python-extension\""]
